"""Noise as Signal — the empirical residual sampler.

Approach (see the project page, §04.5): the residual between video-based
pose estimation and mocap, measured on *paired* recordings of the same
motions, is a structured noise distribution D̂ — and injecting samples from D̂
during policy training regularizes the policy better than synthetic Gaussian
perturbations, because it is generated by the same estimator the deployed
system will actually see.

    q̃(t) = q_m(t) + λ · ε′(t),    ε′ ~ D̂_task

Two properties of ε that a Gaussian throws away, and this sampler preserves:

1. **Per-joint scale.** Wrist error and pelvis error differ by an order of
   magnitude; D̂ is fit per joint, not pooled.
2. **Temporal correlation.** Estimation error drifts and snaps with occlusion
   and contact; it is not white. We sample by **block bootstrap** — contiguous
   windows of *real* residual, resampled — rather than per-frame i.i.d. draws.

Status: under internal validation. This module is the skeleton we run
internal sweeps with; the λ-curriculum and per-task-class conditioning we ship in production
are not in the public SDK.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass
class ResidualBank:
    """Fitted residual store: (n_frames, n_joints, dof) array of real ε samples."""
    residuals: np.ndarray          # concatenated aligned residual sequences
    joint_scale: np.ndarray        # (n_joints,) per-joint RMS — diagnostics + normalization
    block_len: int                 # frames per bootstrap block

    @property
    def n_frames(self) -> int:
        return self.residuals.shape[0]


def fit(pairs: list[tuple[np.ndarray, np.ndarray]], block_len: int = 32) -> ResidualBank:
    """Fit D̂ from paired sequences.

    Parameters
    ----------
    pairs
        List of ``(q_mocap, q_video)`` arrays, each ``(T_i, n_joints, dof)``,
        time-aligned (we align by cross-correlation upstream; alignment is not
        this module's job).
    block_len
        Bootstrap block length in frames. Long enough to keep the error's
        temporal structure, short enough to recombine freely. 32 frames at
        30 fps ≈ 1 s is our default sweep center.
    """
    resids = [qv - qm for qm, qv in pairs]
    residuals = np.concatenate(resids, axis=0)
    joint_scale = np.sqrt((residuals ** 2).mean(axis=(0, 2)))
    return ResidualBank(residuals=residuals, joint_scale=joint_scale, block_len=block_len)


def sample(bank: ResidualBank, n_frames: int, scale: float = 1.0,
           rng: np.random.Generator | None = None) -> np.ndarray:
    """Draw an ε′ sequence of length *n_frames* by block bootstrap, scaled by λ=*scale*.

    Returns ``(n_frames, n_joints, dof)`` — add it to a clean mocap trajectory
    to produce the perturbed training input q̃.
    """
    rng = rng or np.random.default_rng()
    B, T = bank.block_len, bank.n_frames
    if T < B:
        raise ValueError(f"bank too small: {T} frames < block_len {B}")
    out = []
    remaining = n_frames
    while remaining > 0:
        start = int(rng.integers(0, T - B + 1))
        take = min(B, remaining)
        out.append(bank.residuals[start:start + take])
        remaining -= take
    return scale * np.concatenate(out, axis=0)


def perturb(q_mocap: np.ndarray, bank: ResidualBank, scale: float = 1.0,
            rng: np.random.Generator | None = None) -> np.ndarray:
    """q̃ = q_m + λ·ε′ — the one-liner the training loop calls."""
    return q_mocap + sample(bank, len(q_mocap), scale=scale, rng=rng)
